# Generated by Django 4.2.3 on 2023-10-28 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datagenerator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj_karnetu', models.IntegerField()),
                ('cena_karnetu', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='KlientLoyalty',
            fields=[
                ('PESEL', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NadzorTrasy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_nadzoru', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PracaKonserwacyjna',
            fields=[
                ('ID_pracy', models.AutoField(primary_key=True, serialize=False)),
                ('opis_pracy', models.TextField()),
                ('data_rozpoczecia', models.DateField()),
                ('data_zakonczenia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('ID_pracownika', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=100)),
                ('Nazwisko', models.CharField(max_length=100)),
                ('Stanowisko', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemNaStoku',
            fields=[
                ('ID_problemu', models.AutoField(primary_key=True, serialize=False)),
                ('opis_problemu', models.TextField()),
                ('data_zgloszenia', models.DateField()),
                ('data_rozwiazania_problemu', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RejestrPrzejazdow',
            fields=[
                ('ID_przejazdu', models.AutoField(primary_key=True, serialize=False)),
                ('Data', models.DateField()),
                ('ID_karnetu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.karnet')),
            ],
        ),
        migrations.CreateModel(
            name='SprzedazKarnetow',
            fields=[
                ('ID_karnetu', models.AutoField(primary_key=True, serialize=False)),
                ('PESEL_klienta', models.CharField(max_length=11)),
                ('data_zakupu', models.DateField()),
                ('rodzaj_karnetu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.karnet')),
            ],
        ),
        migrations.CreateModel(
            name='TrasaNarciarska',
            fields=[
                ('ID_trasy', models.AutoField(primary_key=True, serialize=False)),
                ('Poziom_trudnosci', models.CharField(max_length=100)),
                ('Dlugosc_trasy', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='rejestrprzejazdow',
            name='ID_trasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.trasanarciarska'),
        ),
        migrations.AddField(
            model_name='problemnastoku',
            name='ID_trasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.trasanarciarska'),
        ),
        migrations.AddField(
            model_name='pracakonserwacyjna',
            name='ID_konserwatora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.pracownik'),
        ),
        migrations.AddField(
            model_name='pracakonserwacyjna',
            name='ID_trasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.trasanarciarska'),
        ),
        migrations.AddField(
            model_name='nadzortrasy',
            name='ID_pracownika',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.pracownik'),
        ),
        migrations.AddField(
            model_name='nadzortrasy',
            name='ID_trasy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datagenerator.trasanarciarska'),
        ),
    ]
